-- Seed Users Data for Testing
-- Password hashes are bcrypt-compatible
-- Admin password: "admin123" - Hash: $2a$10$rKZqN9xqZ5F5QZ5qZ5F5Qu5F5QZ5qZ5F5QZ5qZ5F5QZ5qZ5F5QZ5q (example, will be generated by backend)

-- ===============================================
-- ADMIN (Teacher Role)
-- ===============================================

INSERT INTO users (username, password, fullName, email, role, class, active)
VALUES 
  -- Admin account (username: admin, password: admin123)
  ('admin', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Admin', 'admin@quizfun.edu.vn', 'teacher', NULL, 1);
  -- Note: Password hash is for "password" - will need to update with actual admin123 hash

-- ===============================================
-- STUDENTS - Class 5A
-- ===============================================

INSERT INTO users (username, password, fullName, email, role, class, active)
VALUES 
  ('hs5a01', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Nguyễn Văn An', 'an.nguyen@student.edu.vn', 'student', '5A', 1),
  ('hs5a02', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Trần Thị Bình', 'binh.tran@student.edu.vn', 'student', '5A', 1),
  ('hs5a03', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Lê Văn Cường', 'cuong.le@student.edu.vn', 'student', '5A', 1),
  ('hs5a04', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Phạm Thị Diệu', 'dieu.pham@student.edu.vn', 'student', '5A', 1),
  ('hs5a05', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Hoàng Văn Em', 'em.hoang@student.edu.vn', 'student', '5A', 1),
  ('hs5a06', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Vũ Thị Phương', 'phuong.vu@student.edu.vn', 'student', '5A', 1),
  ('hs5a07', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Đỗ Văn Giang', 'giang.do@student.edu.vn', 'student', '5A', 1),
  ('hs5a08', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Bùi Thị Hà', 'ha.bui@student.edu.vn', 'student', '5A', 1),
  ('hs5a09', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Đinh Văn Ích', 'ich.dinh@student.edu.vn', 'student', '5A', 1),
  ('hs5a10', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Mai Thị Kim', 'kim.mai@student.edu.vn', 'student', '5A', 1);

-- ===============================================
-- STUDENTS - Class 5B
-- ===============================================

INSERT INTO users (username, password, fullName, email, role, class, active)
VALUES 
  ('hs5b01', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Nguyễn Văn Long', 'long.nguyen@student.edu.vn', 'student', '5B', 1),
  ('hs5b02', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Trần Thị Mai', 'mai.tran@student.edu.vn', 'student', '5B', 1),
  ('hs5b03', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Lê Văn Nam', 'nam.le@student.edu.vn', 'student', '5B', 1),
  ('hs5b04', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Phạm Thị Oanh', 'oanh.pham@student.edu.vn', 'student', '5B', 1),
  ('hs5b05', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Hoàng Văn Phúc', 'phuc.hoang@student.edu.vn', 'student', '5B', 1),
  ('hs5b06', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Vũ Thị Quỳnh', 'quynh.vu@student.edu.vn', 'student', '5B', 1),
  ('hs5b07', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Đỗ Văn Rồng', 'rong.do@student.edu.vn', 'student', '5B', 1),
  ('hs5b08', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Bùi Thị Sơn', 'son.bui@student.edu.vn', 'student', '5B', 1),
  ('hs5b09', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Đinh Văn Tú', 'tu.dinh@student.edu.vn', 'student', '5B', 1),
  ('hs5b10', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Mai Thị Uyên', 'uyen.mai@student.edu.vn', 'student', '5B', 1);

-- ===============================================
-- STUDENTS - Class 6A
-- ===============================================

INSERT INTO users (username, password, fullName, email, role, class, active)
VALUES 
  ('hs6a01', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Nguyễn Văn Việt', 'viet.nguyen@student.edu.vn', 'student', '6A', 1),
  ('hs6a02', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Trần Thị Xuân', 'xuan.tran@student.edu.vn', 'student', '6A', 1),
  ('hs6a03', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Lê Văn Yên', 'yen.le@student.edu.vn', 'student', '6A', 1),
  ('hs6a04', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Phạm Thị Ánh', 'anh.pham@student.edu.vn', 'student', '6A', 1),
  ('hs6a05', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'Hoàng Văn Bảo', 'bao.hoang@student.edu.vn', 'student', '6A', 1);
